@startmindmap
'https://plantuml.com/sequence-diagram
title CloudDisk
* <&flag>CloudDisk
** √用户模块
*** √密码登录
*** √邮箱注册
*** √用户详情
*** √刷新Authorization
** √储存池模块
*** √中心储存池资源管理
**** √文件上传
**** 文件下载
**** √文件秒传
**** √文件分片上传
*** √个人储存池资源管理
**** √文件关联存储
**** √文件列表
**** √文件移动
**** √文件删除
**** √文件名称修改
**** √文件夹创建
** √文件共享模块
*** √文件分享

center footer APBC
@endmindmap